spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/test_db
    username: root
    password: root
  flyway:
    url: jdbc:postgresql://localhost:5433/test_db
    user: root
    password: root
